repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.1.0'
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.1.1
          - prettier-plugin-svelte@3.1.2
